Bugfixes and refactoring
notamedia/yii2-sentry pull request #38
Opened 2020-04-13 15:08 UTC by CookiesEater

1. Removed SentryTarget::$client (not used)
2. Changed visibility for SentryTarget::runExtraCallback
3. Added logging user data (ip and user id)
4. For exception logging added additional data (tags, extra, user data)
5. For now every log message used own scope
6. Fixed message level (debug, info, warning, error) translating to sentry
7. Old method SentryTarget::getLevelName removed

2020-04-24 10:45 UTC, niksamokhvalov requested changes
Хорошая работа, надеюсь, ничего из старого функционала не сломали :) 

Есть несколько предложений. Они не связаны с данным ПР, но без них совсем плохо жить.

1. Нужно добиться того, чтобы в ПР тоже запускались проверки TravisCI.
1. Давайте сделаем [команды](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands) `composer test` и `composer e2e`. Первая для запуска Кодсепшена (в .travis.yml вызовы поправить надо будет), вторая — для запуска отправки тестовых логов в Сентри.
1. Добавьте вывод состояния в команду, отправляющую тестовые логи в Сентри. Сейчас непонятно, что происходит — то ли она отправила логи, то ли ничего не произошло из-за того, что sentryDsn в параметрах не был указан.

2020-04-24 10:45 UTC, niksamokhvalov commented on README.md
> +```
Нужно добавить ПХП-стилизацию, читать код неудобно без подсветки синтаксиса.

2020-04-24 10:45 UTC, niksamokhvalov commented on README.md
> +## Additional context
Информация этой главы описывает способы конфигурации логера. Значит эта глава должна быть подглавой Usage.

2020-04-24 10:45 UTC, niksamokhvalov commented on src/SentryTarget.php
> +    protected function runExtraCallback($text, array $extra): array
Нельзя менять уровень видимости у методов, которые могли бы отнаследованы в таргетах пользователей, решивших расширить нашу библиотеку. Нужно либо вернуть предыдущий уровень видимости, либо выпускать мажорный релиз вер. 2. Я за первый вариант.

2020-04-24 10:45 UTC, niksamokhvalov commented on src/SentryTarget.php
> +    protected function runExtraCallback($text, array $extra): array
Кроме того, нельзя удалять метод `getLevelName` (по тем же самым соображениям). Но его можно пометить как `@deprecated`.

2020-04-28 18:54 UTC, CookiesEater commented on README.md
> +```
Добавил стилизацию

2020-04-28 18:55 UTC, CookiesEater commented on README.md
> +## Additional context
Перенёс в Usage главу

2020-04-28 18:55 UTC, CookiesEater commented on src/SentryTarget.php
> +    protected function runExtraCallback($text, array $extra): array
Вернул сигнатуру как была ранее, и вернул метод `getLevelName()` как deprecated

2020-05-07 07:29 UTC, niksamokhvalov approved these changes
Хорошая работа. Как по мне, можно менять дату в ченджлоге и релизить бетку. А через месяц выпускать стабильную версию.

2020-05-18 11:56 UTC, dmhaiduchonak approved these changes

2020-05-18 11:56 UTC, merged